<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>DAW Lab 24</title>
        <link href="https://daw-haperezs.c9users.io/web-service/public/style.css" rel="stylesheet">
    </head>

    <body>
        <header>
            <h1>S1</h1>
        </header>
    
        <h3>Pon al compa en el cuadro.</h3>
        <div id="cuadro" ondrop="drop(event)" ondragover="allowDrop(event)"></div>
        <br>
        <img id="drag1" src="https://daw-haperezs.c9users.io/web-service/public/dude.png" draggable="true" ondragstart="drag(event)" width="300" height="300">


        <script type = "text/javascript" src = "https://daw-haperezs.c9users.io/web-service/public/script.js"></script>
    </body>

</html>
