<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>DAW Lab 24</title>
        <link href="https://daw-haperezs.c9users.io/web-service/public/style.css" rel="stylesheet">
    </head>
    
    <body>
        <header>
            <h1>S2</h1>    
        </header>
        
        <article id = "changetext">
            <h2>Preguntas</h2>
            <ul>
                <li>¿A qué se refiere la descentralización de servicios web?<br>
                    Separar los componentes de una aplicación para que sean accesibles desde fuera
                </li><br>
                <li>¿Cómo puede implementarse un entorno con servicios web disponibles aún cuando falle un servidor?<br>
                    Distribuyendo las funciones
                </li>
            </ul>
        </article>
        
        <script type = "text/javascript" src = "https://daw-haperezs.c9users.io/web-service/public/script.js"></script>
    </body>
</html>
